# 配置选项：https://rust-lang.github.io/rustfmt/

reorder_modules = true
use_small_heuristics = "Max"
condense_wildcard_suffixes = true
imports_granularity = "Crate"
style_edition = "2024"
merge_derives = false
group_imports = "StdExternalCrate"
use_field_init_shorthand = true